version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  version: 2
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run build
