version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  test:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run test
